# Copyright 2021- Rahul De
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

name: Tests

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v5"

      - name: "Prepare Java"
        uses: "actions/setup-java@v5"
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: "Prepare tools-deps"
        uses: "DeLaGuardo/setup-clojure@master"
        with:
          cli: latest

      - name: "Apply Cache"
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.m2/repository
          key: "${{ runner.os }}-navi-${{ hashFiles('deps.edn') }}"
          restore-keys: "${{ runner.os }}-navi-"

      - name: "Run tests"
        run: "clojure -X:test"
